const PLATFORMS = [
  {
    id: 'youtube',
    name: 'YouTube',
    icon: '▶',
    color: '#FF0000',
    category: 'video',
    tags: ['videos', 'shorts', 'live', 'music', 'tutorials'],
    monthlyUsers: '2.7B',
    contentTypes: ['Videos', 'Shorts', 'Live Streams', 'Playlists'],
    searchUrl: (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`,
    shortsUrl: (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}&sp=EgIYAQ%253D%253D`,
    liveUrl: (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}&sp=EgJAAQ%253D%253D`,
    channelUrl: (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}&sp=EgIQAg%253D%253D`,
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    icon: '♪',
    color: '#69C9D0',
    colorSecondary: '#EE1D52',
    category: 'short',
    tags: ['reels', 'shorts', 'trends', 'challenges', 'viral'],
    monthlyUsers: '1.5B',
    contentTypes: ['Short Videos', 'Live', 'Stories'],
    searchUrl: (q) => `https://www.tiktok.com/search?q=${encodeURIComponent(q)}`,
    liveUrl: (q) => `https://www.tiktok.com/search?q=${encodeURIComponent(q)}&type=live`,
    userUrl: (q) => `https://www.tiktok.com/search?q=${encodeURIComponent(q)}&type=user`,
  },
  {
    id: 'instagram',
    name: 'Instagram',
    icon: '◎',
    color: '#E1306C',
    colorSecondary: '#F77737',
    category: 'social',
    tags: ['reels', 'stories', 'photos', 'explore'],
    monthlyUsers: '2.4B',
    contentTypes: ['Reels', 'Posts', 'Stories', 'Live'],
    searchUrl: (q) => `https://www.instagram.com/explore/tags/${encodeURIComponent(q.replace(/ /g, ''))}/`,
    reelsUrl: (q) => `https://www.instagram.com/reels/audio/`,
    exploreUrl: () => `https://www.instagram.com/explore/`,
  },
  {
    id: 'facebook',
    name: 'Facebook',
    icon: 'f',
    color: '#1877F2',
    category: 'social',
    tags: ['videos', 'reels', 'live', 'stories'],
    monthlyUsers: '3.0B',
    contentTypes: ['Videos', 'Reels', 'Live', 'Stories'],
    searchUrl: (q) => `https://www.facebook.com/search/videos/?q=${encodeURIComponent(q)}`,
    reelsUrl: (q) => `https://www.facebook.com/reels/`,
    liveUrl: (q) => `https://www.facebook.com/search/live/?q=${encodeURIComponent(q)}`,
  },
  {
    id: 'twitter',
    name: 'X / Twitter',
    icon: '✕',
    color: '#e7e7e7',
    category: 'social',
    tags: ['videos', 'clips', 'news', 'trending'],
    monthlyUsers: '550M',
    contentTypes: ['Video Tweets', 'Clips', 'Spaces'],
    searchUrl: (q) => `https://twitter.com/search?q=${encodeURIComponent(q)}&f=video`,
    liveUrl: (q) => `https://twitter.com/search?q=${encodeURIComponent(q)}&f=live`,
    topUrl: (q) => `https://twitter.com/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: '◈',
    color: '#9146FF',
    category: 'live',
    tags: ['gaming', 'live', 'streams', 'esports'],
    monthlyUsers: '140M',
    contentTypes: ['Live Streams', 'Clips', 'VODs', 'Categories'],
    searchUrl: (q) => `https://www.twitch.tv/search?term=${encodeURIComponent(q)}`,
    clipsUrl: (q) => `https://www.twitch.tv/search?term=${encodeURIComponent(q)}&type=clips`,
    categoryUrl: (q) => `https://www.twitch.tv/search?term=${encodeURIComponent(q)}&type=categories`,
  },
  {
    id: 'reddit',
    name: 'Reddit',
    icon: '◍',
    color: '#FF4500',
    category: 'community',
    tags: ['videos', 'gifs', 'clips', 'community'],
    monthlyUsers: '1.5B',
    contentTypes: ['Video Posts', 'GIFs', 'Communities'],
    searchUrl: (q) => `https://www.reddit.com/search/?q=${encodeURIComponent(q)}&type=video`,
    communityUrl: (q) => `https://www.reddit.com/search/?q=${encodeURIComponent(q)}&type=sr`,
    newUrl: (q) => `https://www.reddit.com/search/?q=${encodeURIComponent(q)}&sort=new`,
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    icon: '◐',
    color: '#1AB7EA',
    category: 'video',
    tags: ['hd', 'creative', 'professional', 'films'],
    monthlyUsers: '300M',
    contentTypes: ['HD Videos', 'Films', 'Portfolios'],
    searchUrl: (q) => `https://vimeo.com/search?q=${encodeURIComponent(q)}`,
    channelUrl: (q) => `https://vimeo.com/search?q=${encodeURIComponent(q)}&type=channel`,
  },
  {
    id: 'dailymotion',
    name: 'Dailymotion',
    icon: '◉',
    color: '#0066DC',
    category: 'video',
    tags: ['videos', 'news', 'entertainment', 'sports'],
    monthlyUsers: '300M',
    contentTypes: ['Videos', 'Live', 'Channels', 'Playlists'],
    searchUrl: (q) => `https://www.dailymotion.com/search/${encodeURIComponent(q)}`,
    liveUrl: (q) => `https://www.dailymotion.com/search/${encodeURIComponent(q)}/1#live`,
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    icon: '◌',
    color: '#FFFC00',
    category: 'social',
    tags: ['stories', 'spotlight', 'snaps', 'filters'],
    monthlyUsers: '750M',
    contentTypes: ['Spotlight', 'Stories', 'Snaps'],
    searchUrl: (q) => `https://www.snapchat.com/search?q=${encodeURIComponent(q)}`,
    spotlightUrl: () => `https://www.snapchat.com/spotlight`,
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    icon: '⊕',
    color: '#E60023',
    category: 'visual',
    tags: ['ideas', 'visual', 'pins', 'inspiration'],
    monthlyUsers: '465M',
    contentTypes: ['Video Pins', 'Idea Pins', 'Boards'],
    searchUrl: (q) => `https://www.pinterest.com/search/pins/?q=${encodeURIComponent(q)}&rs=typed`,
    videoUrl: (q) => `https://www.pinterest.com/search/pins/?q=${encodeURIComponent(q)}&rs=typed&term_meta[]=video`,
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'in',
    color: '#0A66C2',
    category: 'professional',
    tags: ['professional', 'business', 'networking', 'learning'],
    monthlyUsers: '900M',
    contentTypes: ['Video Posts', 'Learning', 'Live Events'],
    searchUrl: (q) => `https://www.linkedin.com/search/results/videos/?keywords=${encodeURIComponent(q)}`,
    postUrl: (q) => `https://www.linkedin.com/search/results/content/?keywords=${encodeURIComponent(q)}`,
  },
  {
    id: 'rumble',
    name: 'Rumble',
    icon: 'R',
    color: '#85C742',
    category: 'video',
    tags: ['videos', 'news', 'independent', 'live'],
    monthlyUsers: '50M',
    contentTypes: ['Videos', 'Live', 'Channels'],
    searchUrl: (q) => `https://rumble.com/search/video?q=${encodeURIComponent(q)}`,
    liveUrl: (q) => `https://rumble.com/search/live?q=${encodeURIComponent(q)}`,
  },
  {
    id: 'odysee',
    name: 'Odysee',
    icon: '∞',
    color: '#EF1970',
    category: 'decentralized',
    tags: ['blockchain', 'decentralized', 'independent', 'free'],
    monthlyUsers: '30M',
    contentTypes: ['Videos', 'Livestreams', 'Channels'],
    searchUrl: (q) => `https://odysee.com/$/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: 'bilibili',
    name: 'Bilibili',
    icon: 'B',
    color: '#FB7299',
    category: 'video',
    tags: ['anime', 'gaming', 'chinese', 'tutorials'],
    monthlyUsers: '300M',
    contentTypes: ['Videos', 'Live', 'Anime', 'Gaming'],
    searchUrl: (q) => `https://search.bilibili.com/all?keyword=${encodeURIComponent(q)}`,
  },
  {
    id: 'triller',
    name: 'Triller',
    icon: 'T',
    color: '#FF0069',
    category: 'short',
    tags: ['music', 'short videos', 'trends'],
    monthlyUsers: '65M',
    contentTypes: ['Music Videos', 'Short Clips'],
    searchUrl: (q) => `https://triller.co/search?q=${encodeURIComponent(q)}`,
  },
  {
    id: 'kwai',
    name: 'Kwai',
    icon: 'K',
    color: '#FF8200',
    category: 'short',
    tags: ['short videos', 'fun', 'viral'],
    monthlyUsers: '200M',
    contentTypes: ['Short Videos', 'Live'],
    searchUrl: (q) => `https://www.kwai.com/search?keyword=${encodeURIComponent(q)}`,
  },
  {
    id: 'peertube',
    name: 'PeerTube',
    icon: 'P',
    color: '#F1680D',
    category: 'decentralized',
    tags: ['federated', 'open source', 'independent'],
    monthlyUsers: '5M',
    contentTypes: ['Videos', 'Live'],
    searchUrl: (q) => `https://search.joinpeertube.org/search?search=${encodeURIComponent(q)}`,
  },
];

const PLATFORM_CATEGORIES = [
  { id: 'all', label: 'All Platforms', icon: '⬡' },
  { id: 'video', label: 'Video', icon: '▶' },
  { id: 'social', label: 'Social', icon: '◎' },
  { id: 'short', label: 'Shorts', icon: '♪' },
  { id: 'live', label: 'Live', icon: '◈' },
  { id: 'community', label: 'Community', icon: '◍' },
  { id: 'visual', label: 'Visual', icon: '⊕' },
  { id: 'professional', label: 'Professional', icon: 'in' },
  { id: 'decentralized', label: 'Decentralized', icon: '∞' },
];

const getPlatformById = (id) => PLATFORMS.find(p => p.id === id);
const getPlatformsByCategory = (cat) => cat === 'all' ? PLATFORMS : PLATFORMS.filter(p => p.category === cat);

module.exports = { PLATFORMS, PLATFORM_CATEGORIES, getPlatformById, getPlatformsByCategory };
